# Generated by Django 3.2.3 on 2021-06-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20210616_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[("('billing', 'Billing address')", 'Billing'), ("('shipping', 'Shipping address')", 'Shipping')], default="('billing', 'Billing address')", max_length=120),
        ),
    ]
