# Generated by Django 3.2.3 on 2021-06-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseSectionProxy',
        ),
        migrations.RemoveField(
            model_name='course',
            name='lecture',
        ),
        migrations.RemoveField(
            model_name='course',
            name='lectures',
        ),
        migrations.RemoveField(
            model_name='courseitem',
            name='lecture',
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('deep', 'Deep Dive'), ('featured', 'Featured')], default='basic', max_length=120),
        ),
    ]
