# Generated by Django 3.2.3 on 2021-07-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20210622_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='headline',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
