# Generated by Django 3.2.3 on 2021-06-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='order',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=39.99, max_digits=20, null=True),
        ),
    ]
