# Generated by Django 3.2.3 on 2021-07-30 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_parent'),
        ('courses', '0006_auto_20210730_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catCourses', to='categories.category'),
        ),
    ]
