# Generated by Django 3.2.3 on 2021-07-10 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210709_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningoutcome',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabuses', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='titledescription',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='included', to='projects.project'),
        ),
    ]
