# Generated by Django 3.2.3 on 2021-08-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_state'),
        ('projects', '0005_auto_20210805_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects', to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='project',
            name='goal',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='header_primary_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='header_secondary_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='hero',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='video_headline',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
