# Generated by Django 3.2.3 on 2021-08-06 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_state'),
        ('projects', '0008_auto_20210805_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='projects', to='courses.Course'),
        ),
    ]
