# Generated by Django 3.2.3 on 2021-08-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='completion_time',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
