# Generated by Django 3.2.3 on 2021-08-08 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_project_completion_time'),
        ('carts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='courses',
        ),
        migrations.AddField(
            model_name='cart',
            name='projects',
            field=models.ManyToManyField(blank=True, to='projects.Project'),
        ),
    ]
