# Generated by Django 3.2.3 on 2021-08-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_lectureprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectureprogress',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
