# Generated by Django 3.2.3 on 2021-08-15 22:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_lectureprogress_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureprogress',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lectureprogress',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
