# Generated by Django 3.2.3 on 2021-08-02 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0002_rename_skills_instructor_tags'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='instructor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='instructors.instructor'),
            preserve_default=False,
        ),
    ]
