# Generated by Django 3.2.3 on 2021-08-18 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_project_thumbnail_url'),
        ('instructors', '0005_instructor_avatar'),
        ('pricing', '0002_pricing_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(choices=[('50', '50'), ('100', '100'), ('200', '200'), ('300', '300'), ('400', '400'), ('500', '500')], default='50', max_length=5)),
                ('currency', models.CharField(choices=[('GHS', 'GHS'), ('USD', 'USD'), ('GBP', 'GBP')], default='USD', max_length=4)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructors.instructor')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='projects.project')),
            ],
        ),
    ]
