# Generated by Django 3.2.3 on 2021-08-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_projectpricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='currency',
            field=models.CharField(choices=[('GHS', 'GHS'), ('$', 'USD'), ('£', 'GBP')], default='$', max_length=4),
        ),
        migrations.AlterField(
            model_name='projectpricing',
            name='currency',
            field=models.CharField(choices=[('GHS', 'GHS'), ('$', 'USD'), ('£', 'GBP')], default='$', max_length=4),
        ),
    ]
