# Generated by Django 3.2.3 on 2021-07-09 19:39

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instructors', '0002_rename_skills_instructor_tags'),
        ('courses', '0005_auto_20210622_0102'),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningOutCome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('lead', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=200)),
                ('goal', models.CharField(max_length=120)),
                ('hero', models.CharField(max_length=120)),
                ('experience', models.CharField(choices=[('Beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('deep', 'Deep Dive')], default='Beginner', max_length=12)),
                ('completion_time', models.CharField(max_length=120)),
                ('header_primary_color', models.CharField(max_length=100)),
                ('header_secondary_color', models.CharField(max_length=100)),
                ('video_headline', models.CharField(max_length=200)),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('deep', 'Deep Dive')], default='Beginner', max_length=20)),
                ('progress', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=3, max_length=100, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=39.99, max_digits=20, null=True)),
                ('state', models.CharField(choices=[('LIVE', 'Live'), ('DR', 'Draft'), ('PD', 'Pending'), ('DEL', 'Deleted')], default='DR', max_length=20)),
                ('publish_timestamp', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('courses', models.ManyToManyField(related_name='projects', to='courses.Course')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=120)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('occupation', models.CharField(max_length=120)),
                ('quote', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TitleDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRelated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_item', to='projects.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectsection'),
        ),
        migrations.AddField(
            model_name='project',
            name='includes',
            field=models.ManyToManyField(blank=True, null=True, to='projects.TitleDescription'),
        ),
        migrations.AddField(
            model_name='project',
            name='instructor',
            field=models.ManyToManyField(related_name='projects', to='instructors.Instructor'),
        ),
        migrations.AddField(
            model_name='project',
            name='outcomes',
            field=models.ManyToManyField(blank=True, null=True, to='projects.LearningOutCome'),
        ),
        migrations.AddField(
            model_name='project',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='_projects_project_related_+', through='projects.ProjectRelated', to='projects.Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='projects.syllabus'),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='project',
            name='testimonial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.testimonial'),
        ),
    ]
