# Generated by Django 3.2.3 on 2021-07-09 20:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='includes',
        ),
        migrations.RemoveField(
            model_name='project',
            name='outcomes',
        ),
        migrations.RemoveField(
            model_name='project',
            name='syllabus',
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='syllabus',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='syllabus',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='titledescription',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='titledescription',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='titledescription',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
