# Generated by Django 3.2.3 on 2021-08-03 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210710_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.CharField(choices=[('LIVE', 'Live'), ('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('DELETE', 'Deleted')], default='DRAFT', max_length=20),
        ),
    ]
