# Generated by Django 3.2.3 on 2021-08-05 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0005_instructor_avatar'),
        ('projects', '0004_alter_project_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningoutcome',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='projectrelated',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='syllabus',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='titledescription',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instructors.instructor'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instructors.instructor'),
        ),
        migrations.AddField(
            model_name='titledescription',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instructors.instructor'),
        ),
        migrations.AlterField(
            model_name='learningoutcome',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='project',
            name='header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.projectsection'),
        ),
        migrations.AlterField(
            model_name='projectrelated',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='titledescription',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
    ]
