# Generated by Django 3.2.3 on 2021-08-05 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0005_instructor_avatar'),
        ('projects', '0007_rename_instructor_project_instructors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='instructors',
        ),
        migrations.AddField(
            model_name='project',
            name='instructor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='instructors.instructor'),
            preserve_default=False,
        ),
    ]
