# Generated by Django 3.2.3 on 2021-08-09 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_categories', '0002_alter_projectcategory_options'),
        ('projects', '0010_alter_project_completion_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_categories.projectcategory'),
        ),
    ]
