# Generated by Django 3.2.3 on 2021-08-09 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0005_instructor_avatar'),
        ('projects', '0011_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsection',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instructors.instructor'),
        ),
    ]
