# Generated by Django 3.2.3 on 2021-08-18 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_project_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
