# Generated by Django 3.2.3 on 2021-06-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lead',
            field=models.TextField(blank=True, null=True),
        ),
    ]
