# Generated by Django 3.2.3 on 2021-06-22 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='lead',
            field=models.BooleanField(default=False),
        ),
    ]
