# Generated by Django 3.2.3 on 2021-06-15 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='skills',
            new_name='tags',
        ),
    ]
