# Generated by Django 3.2.3 on 2021-08-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0002_rename_skills_instructor_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='about_me',
            new_name='description',
        ),
        migrations.AddField(
            model_name='instructor',
            name='headline',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
