# Generated by Django 3.2.3 on 2021-07-27 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_projectfile'),
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='resources',
            field=models.ManyToManyField(blank=True, null=True, related_name='lectures', to='files.CourseFile'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecture', to='files.coursefile'),
        ),
    ]
