# Generated by Django 3.2.3 on 2021-07-28 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0004_auto_20210727_2336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='section',
            name='neighbor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lectures.section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=2, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
