# Generated by Django 3.2.3 on 2021-08-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0009_alter_lecture_state'),
    ]

    operations = [
        
        migrations.RemoveField(
            model_name='lecture',
            name='duration',
        ),
        migrations.AddField(
            model_name='lecture',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
