# Generated by Django 3.2.3 on 2021-08-17 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_state'),
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='courses.course'),
        ),
    ]
