# Generated by Django 3.2.3 on 2021-07-11 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210710_0020'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=220, null=True)),
                ('key', models.TextField()),
                ('filetype', models.CharField(default='video/mp4', max_length=120)),
                ('uploaded', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('size', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('duration', models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='projects.project')),
            ],
        ),
    ]
