# Generated by Django 3.2.3 on 2021-08-09 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'verbose_name': 'Project Category', 'verbose_name_plural': 'Project Categories'},
        ),
    ]
