# Generated by Django 3.2.3 on 2021-08-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_auto_20210815_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureprogress',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
