# Generated by Django 3.2.3 on 2021-06-13 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_tags'),
        ('files', '0002_coursefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefile',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='courses.course'),
        ),
    ]
