# Generated by Django 3.2.3 on 2021-05-25 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('lecture_id', models.CharField(max_length=220, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('PU', 'Publish'), ('DR', 'Draft')], default='DR', max_length=2)),
                ('publish_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LecturePublishedProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Published Lecture',
                'verbose_name_plural': 'Published Lectures',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('lectures.lecture',),
        ),
    ]
