# Generated by Django 3.2.3 on 2021-06-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='state',
            field=models.CharField(choices=[('LIVE', 'Live'), ('DR', 'Draft'), ('PD', 'Pending'), ('DEL', 'Deleted')], default='DR', max_length=4),
        ),
    ]
