# Generated by Django 3.2.3 on 2021-07-27 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0002_rename_skills_instructor_tags'),
        ('files', '0002_projectfile'),
        ('lectures', '0002_auto_20210727_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='user',
        ),
        migrations.RemoveField(
            model_name='section',
            name='user',
        ),
        migrations.AddField(
            model_name='lecture',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instructors.instructor'),
        ),
        migrations.AddField(
            model_name='section',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instructors.instructor'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='resources',
            field=models.ManyToManyField(related_name='lectures', to='files.CourseFile'),
        ),
    ]
