# Generated by Django 3.2.3 on 2021-06-06 19:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210606_1917'),
        ('lectures', '0002_alter_lecture_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=220, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lecture',
            name='title',
            field=models.CharField(max_length=220),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.course')),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='lectures.section'),
        ),
    ]
