# Generated by Django 3.2.3 on 2021-06-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0003_auto_20210606_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, null=True),
        ),
    ]
