# Generated by Django 3.2.3 on 2021-07-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0003_auto_20210727_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='order',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='order',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
