# Generated by Django 3.2.3 on 2021-06-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0004_alter_lecture_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='video_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
