# Generated by Django 3.2.3 on 2021-06-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0005_lecture_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='filename',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
