# Generated by Django 3.2.3 on 2021-07-28 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0005_auto_20210728_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='position',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
