# Generated by Django 3.2.3 on 2021-07-29 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_projectfile'),
        ('lectures', '0007_auto_20210729_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='lectures', to='files.CourseFile'),
        ),
    ]
