# Generated by Django 3.2.3 on 2021-08-03 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0008_alter_lecture_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='state',
            field=models.CharField(choices=[('LIVE', 'Live'), ('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('DELETE', 'Deleted')], default='DRAFT', max_length=8),
        ),
    ]
