# Generated by Django 3.2.3 on 2021-06-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210616_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_final',
            field=models.TextField(blank=True, null=True),
        ),
    ]
