"""
Django settings for readux project.

Generated by 'django-admin startproject' using Django 3.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u6v9ldfcj@5(jvz@&%#j&%4t$6vjin3lynb#i)ue#&r=gr)5)g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ACCOUNT_ADAPTER = 'accounts.adapter.AccountAdapter'

ALLOWED_HOSTS = [
    '659e1bdcb7d2.ngrok.io',
    'localhost',
    '127.0.0.1',
]

CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000'
]

# EMAIL_HOST = 'smtp.mandrillapp.com'
# EMAIL_HOST_USER = 'Readuced AI'
# EMAIL_MAIN = 'support@readuced.com'
# EMAIL_HOST_PASSWORD = 'BoIsMTtOhFmKjnEQCfjz8w'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True

# GMAIL

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'readingfo@gmail.com'
EMAIL_MAIN = 'akrahsam@gmail.com'
EMAIL_HOST_PASSWORD = '2wsx!QAZ'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'storages',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_auth',
    'rest_auth.registration',
    'algoliasearch_django',

    'widget_tweaks',
    'phonenumber_field',
    'taggit',
    'taggit_serializer',

    'lectures',
    'courses',
    'projects',
    'tags',
    'ratings',
    'billing',
    'categories',
    'marketing',
    'addresses',
    'carts',
    'dashboard',
    'students',
    'instructors',
    'accounts',
    'blogs',
    'orders',
    'reviews',
    'files',
    'auths',
    'corsheaders'

]

SITE_ID = 1

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    },

    'facebook': {
        'METHOD': 'oauth2',
        'SDK_URL': '//connect.facebook.net/{locale}/sdk.js',
        'SCOPE': ['email', 'public_profile'],
        'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
        'INIT_PARAMS': {'cookie': True},
        'FIELDS': [
            'id',
            'first_name',
            'last_name',
            'middle_name',
            'name',
            'name_format',
            'picture',
            'short_name'
        ],
        'EXCHANGE_TOKEN': True,
        'LOCALE_FUNC': lambda request: 'en_US',
        'VERIFIED_EMAIL': True,
        'VERSION': 'v7.0',
    }
}


WISTIA_API_KEY = "0e689ffc12f3301907b32a286a4b61e473a8eb7edb2b464250a32ab38c3b963b"
WISTIA_PUB_TOKEN ="32rhsq7ev3"

VIMEO_CLIENT_ID = "343e022506e1398ceb8c6c41a495dadef20670f4"
VIMEO_SECRET_KEY= "OLa6E8adqXCGUOFV+j9YPe1y2CUWSIn2SusyZZKhCStZoBnQdsTWnQVdLkKYL10+orUFIWFJtdE22k6uA8HJD5Laj1uYQuQj408HE8J6MRls3Cj20OxIwS9IeyT0l0Gl"
VIMEO_ACCESS_TOKEN = '2836b1367a9d045600f218cc0aeea6fc'

MAILCHIMP_API_KEY = "629b4f097db6f6223ce8fb689dab8048-us6"
MAILCHIMP_DATA_CENTER = "us6"
MAILCHIMP_EMAIL_LIST_ID = "937229c102"

PAYPAL_ACCOUNT_ID = "support@readuced.com"
PAYPAL_CLIENT_ID = "AUj_QTk083Xh7ncvSyMDik4La6zALHWM83BEM5SLLkR5ME2nhANowpy1Xm7xc5GUzLXy7b0Wg8NawuPm"
PAYPAL_SECRET_KEY = "EBqXgnp3v_lGVfYLQnk8MutLwr9-kv5bDAwerrEYvALztz-O-5aTC-_0V5qVu1zyLdLXrVkZv5PCKJv_"



ALGOLIA = {
    'APPLICATION_ID': 'B7L92X5LLP',
    'API_KEY': 'e1725a8f66d9948c03c93bcfeeeea435',
    'SEARCH_API_KEY': 'ae3851a6e1c6e04921189356712af9dd'
}



STRIPE_SECRET_KEY = "sk_test_51IuiBEEGT3FsopRecguN7VzWd4iLmEnz0OAJsoJpecdsoZIDPawMMBVgdwbIO7o2QRMqXG22AWLCA0d7VU1vl4um00y0F26TVT"
STRIPE_PUB_KEY = 'pk_test_51IuiBEEGT3FsopReEwvQT7so89xIHyGsrQ1vPkFpSussBn31dBzm6K6lEccpTmPrT6YMBgSpr9aWUlBSYN6Fh4yX0089dFARIb'



AUTHENTICATION_BACKENDS = [
   
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
   
]

ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 7
ACCOUNT_EMAIL_VERIFICATION = 'optional'
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_SIGNUP_REDIRECT_URL = '/'
LOGIN_REDIRECT_URL = '/'
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_LOGOUT_ON_GET = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]

ROOT_URLCONF = 'readux.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'files.context_processors.avatar_processor',
                'accounts.context_processors.login_ctx.login_form_ctx',
            ],
        },
    },
]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    )
}



WSGI_APPLICATION = 'readux.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True




DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

from readux.localstatic import *
from readux.aws.conf import *